### ISSUE TITLE
Video resolution

### ISSUE THREAD

**Issue by rogerio02** [pascaldevink/TweakersConstraintBundle#1]
Is it possible to add a video resolution to de channel?

**Comment by pascaldevink** [comment]
Not sure what you mean? Could you explain a bit more what your request entails and what you're trying to achieve?

**Comment by rogerio02** [comment]
What I mean if it is possible to have on the tweakers channel a higher video quality, on the site you can choose between 360, 720 and 1080p resolution, on plex you only have SD quality.

**Comment by pascaldevink** [comment]
I'm pretty sure you have the wrong repository here. This repository has nothing to do with video's or plex. The 'Tweakers' in the name might've thrown you off, but this repository just has some code that Tweakers open sources, that's it. Also, I no longer work at Tweakers, so this is not the channel to send in feature request :stuck_out_tongue_winking_eye: 
That said, if you want to do a feature request at Tweakers, this is the place: http://gathering.tweakers.net/forum/list_topics/39
